Repository jacksrm/wheres-my-color-frontend, pull requests merged in 2021-12, with the labels that each got.

#18 Jacson Rodrigues - Implementa botão remover paleta
  src/components/PalettePreview/index.tsx
  src/context/UserProvider.tsx
  src/types/index.ts
Labels: code review

#19 Jacson Rodrigues - Implementa função adicionar cor
  src/components/AddColor/index.css
  src/components/AddColor/index.tsx
  src/components/ColorsGallery/index.tsx
  src/components/Loading/index.css
  src/components/Loading/index.tsx
  src/components/OverlayContainer/index.css
  src/components/PalettePreview/index.tsx
  src/context/PaletteProvider.tsx
  src/context/UserProvider.tsx
  src/pages/MyHome/index.css
  src/pages/MyHome/index.tsx
  src/pages/Palette/index.tsx
  src/types/index.ts
Labels: code review

#20 Jacson Rodrigues - Edit palette
  src/components/AddButton/index.css
  src/components/ColorsGallery/index.css
  src/components/ColorsGallery/index.tsx
  src/components/EditPalette/index.css
  src/components/EditPalette/index.tsx
  src/components/Loading/index.tsx
  src/components/PalettePreview/index.css
  src/components/PalettePreview/index.tsx
  src/context/PaletteProvider.tsx
  src/pages/MyHome/index.tsx
  src/pages/Palette/index.tsx
  src/types/index.ts
Labels: code review

#22 Emanuelle - Add logout
  src/components/Header/index.tsx
  src/context/LoginProvider.tsx
  src/types/index.ts
  src/utils/Logout.ts
Labels: bug

#23 Emanuelle - logout
  src/components/Header/index.tsx
Labels: code review

#24 Jacson Rodrigues - Implementa pesquisa de usuários e outros fix
  src/app.tsx
  src/components/AddColor/index.tsx
  src/components/ColorsGallery/index.css
  src/components/ColorsGallery/index.tsx
  src/components/EditInput/index.tsx
  src/components/Header/index.css
  src/components/Header/index.tsx
  src/components/PalettePreview/index.tsx
  src/components/SearchBar/index.css
  src/components/SearchBar/index.tsx
  src/components/SuccessMessage/index.tsx
  src/context/LoginProvider.tsx
  src/context/UserProvider.tsx
  src/hooks/useCheckCLickOutside.ts
  src/pages/Account/index.tsx
  src/pages/Initial/index.tsx
  src/pages/MyHome/index.css
  src/pages/MyHome/index.tsx
  src/pages/NotFound/index.css
  src/pages/NotFound/index.tsx
  src/pages/Palette/index.css
  src/pages/Palette/index.tsx
  src/pages/Registration/index.tsx
  src/pages/Test.tsx
  src/reportWebVitals.ts
  src/types/index.ts
  src/utils/LocalStorage.ts
  src/utils/Logout.ts
Labels: code review

#25 Jacson Rodrigues - Implementa funcionalidade para copiar um link de compartilhamento
  src/components/PalettePreview/index.tsx
Labels: code review

#27 jacson Rodrigues - Fix bug botão excluir cor aparecendo em outros usuários quando logado
  src/components/Color/index.tsx
Labels: bug, code review
